name: aegis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.2.0=py311h66f275b_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311h03d9500_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cpython=3.11.14=py311hd8ed1ab_3
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_2
  - gnutls=3.6.13=h85f3911_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45.1=bootstrap_ha15bf96_1
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h0b41bf4_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran-ng=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libgomp=15.2.0=he0feb66_17
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.41.3=h5347b49_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py311h3778330_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.2=py311h2e04523_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pillow=9.4.0=py311h50def17_1
  - pip=26.0.1=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.9=hb806964_0_cpython
  - python_abi=3.11=8_cp311
  - pytorch=2.5.1=py3.11_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h3778330_1
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - setuptools=82.0.0=pyh332efcf_0
  - tbb=2021.7.0=h924138e_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.5.1=py311_cu121
  - torchtriton=3.1.0=py311
  - torchvision=0.20.1=py311_cu121
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yaml=0.2.5=h280c20c_3
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py311h49ec1c0_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - altair==6.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - click==8.3.1
      - click-default-group==1.2.4
      - contourpy==1.3.3
      - coverage==7.13.4
      - cycler==0.12.1
      - datasets==4.5.0
      - dill==0.4.0
      - fastapi==0.128.8
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - iniconfig==2.3.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - multidict==6.7.1
      - multiprocess==0.70.18
      - narwhals==2.16.0
      - nvidia-ml-py==13.590.48
      - pandas==2.3.3
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - pyarrow==23.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pygments==2.19.2
      - pynvml==13.0.1
      - pyparsing==3.3.2
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - referencing==0.37.0
      - regex==2026.1.15
      - rich==14.3.2
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - seaborn==0.13.2
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sqlite-fts4==1.0.3
      - sqlite-utils==3.39
      - starlette==0.52.1
      - streamlit==1.54.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.4
      - tokenizers==0.22.2
      - toml==0.10.2
      - tornado==6.5.4
      - tqdm==4.67.3
      - transformers==5.1.0
      - typer==0.23.0
      - typer-slim==0.23.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - websockets==16.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/tanveerkaur1292/anaconda3/envs/aegis
